FROM eclipse-mosquitto:latest

LABEL maintainer="maintainer@greengear.app"
LABEL description="Mosquitto MQTT Broker"

COPY mosquitto.conf /mosquitto/config/mosquitto.conf

EXPOSE 1883

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
