mqtt:
  host: "mosquitto"
  port: 1883
  topics:
    - "sensor/data"
    - "actuator/command"

TOKEN:
  HUB_NAME: "Zeus"
  HUB_VESION: "1.2"
  HUB_TOKEN: "4822f41a7fc6955a105e8e367e8d8eeb"

API_ADDRESS: "http://192.168.1.13:8000/"
