# Use the official Node.js runtime as a parent image
FROM node:14

# Installer netcat
RUN apt-get update && apt-get install -y netcat
RUN apt-get update && apt-get install -y postgresql-client
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install && npm install -g ts-node typescript

# Copie du script d'entrée et rendu exécutable
COPY entrypoint.sh /usr/src/app/
RUN chmod +x /usr/src/app/entrypoint.sh

# Bundle the app source code
COPY . .

# Expose the port your app will run on
EXPOSE 8000

# Define the command to run your app
CMD ["/usr/src/app/entrypoint.sh"]