FROM debian:bookworm

# Installation de hostapd
RUN apt-get update && apt-get install -y \
    hostapd \
    iptables \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copie de la configuration de hostapd (vous devrez créer ce fichier)
COPY hostapd.conf /etc/hostapd/hostapd.conf

# Commande pour démarrer hostapd (ajustez selon besoin)
CMD ["hostapd", "-d", "/etc/hostapd/hostapd.conf"]
